# Generated by Django 5.1.6 on 2025-03-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_asignatura_options_alter_grado_options_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_grupo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.grupo'),
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
            ],
            options={
                'unique_together': {('docente', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='asignaturas',
            field=models.ManyToManyField(through='usuarios.DocenteAsignatura', to='academico.asignatura'),
        ),
        migrations.CreateModel(
            name='DocenteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
            options={
                'unique_together': {('docente', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='grupos',
            field=models.ManyToManyField(through='usuarios.DocenteGrupo', to='academico.grupo'),
        ),
    ]
