# Generated by Django 5.1.6 on 2025-02-27 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado', to='academico.grado')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
            options={
                'unique_together': {('id_grupo', 'id_asignatura')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='asignaturas_asignadas',
            field=models.ManyToManyField(through='academico.GrupoAsignatura', to='academico.asignatura'),
        ),
    ]
