# Generated by Django 5.1.6 on 2025-03-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['nombre'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
